### ISSUE TITLE
libasyncd + Free Pascal, is it possible?

### ISSUE THREAD

**Issue by silvioprog** [wolkykim/libasyncd#12]
Hello,

Firstly, thanks for share this nice library, I did some tests (using helloworld_http_server demo) with JMeter and I'm impressed with libasyncd performance, it's so fast like Civetweb HTTP server and NodeJS! =)

However, I don't know C, so I can't understand libasyncd sources to check about this possibility: to use the libasyncd.so/dll to create a HTTP/HTTPS server with Free Pascal [¹].

[¹] [Creating bindings for C libraries](http://wiki.freepascal.org/Creating_bindings_for_C_libraries).

**Comment by wolkykim** [comment]
Do you want to use in Pascal code? Really? Seriously?

**Comment by silvioprog** [comment]
Yes, I do. I already use other libs, like Zlib, OpenSSL etc., now I need from a fast HTTP(S) server, to create a new broker to my framework[¹].

So, can I call some functions like `ad_server_new()`, but externally of your lib? If so, I'll try to create some headers from your lib, otherwise I'll try it with Civetweb[²].

[¹] http://silvioprog.github.io/brookframework
[²] https://github.com/civetweb/civetweb

**Comment by wolkykim** [comment]
I'm not sure because I'm not familiar with it and haven't tried it as well. But I guess if it works with other projects I'd give it a try. Sorry for not helping a lot.

**Comment by silvioprog** [comment]
No problem. I'll try it now! =)
