### ISSUE TITLE
curl: (56) Recv failure: Connection reset by peer when running example

### ISSUE THREAD

**Issue by joprice** [wolkykim/libasyncd#15]
Using the hello world sample code, every few requests, I get  

`curl: (56) Recv failure: Connection reset by peer`

**Comment by wolkykim** [comment]
I guess you might be using helloworld_tcp_server(port 2222) rather than helloworld_http_server(port 8888) example. If this is not the case, please capture both output, server and curl output then post it here please.

**Comment by wolkykim** [comment]
closing the issue since I don't hear back. assuming that was the issue. please reopen if not
