### ISSUE TITLE
Trying asyncd on Windows

### ISSUE THREAD

**Issue by silvioprog** [wolkykim/libasyncd#16]
Hello,

Is `asyncd` library compilable on Windows? I'm trying to compile it, but:

```
fatal error: arpa/inet.h: No such file or directory
```

Based in this error, so I believe that it is only for Unix systems.

Thank you!

**Comment by wolkykim** [comment]
Yes you're right. We haven't took that effort to make it work on windows.
Thanks

**Comment by silvioprog** [comment]
It seems a nice item to a `TODO` list. :-)
