### ISSUE TITLE
get visitor ip address

### ISSUE THREAD

**Issue by levidurfee** [wolkykim/libasyncd#31]
Is there a way I can access the IP address of the visitor? I've looked and looked, but don't see a way.

Thanks!

**Comment by wolkykim** [comment]
I've just added a new function for this purpose.
Please try ad_conn_get_socket() to retrieve the socket associated with a connection.

http://wolkykim.github.io/libasyncd/doc/html/ad__server_8c.html#a5ba67b542d4ba48ad4a25280d10ef86f

**Comment by levidurfee** [comment]
Thanks so much!
