### ISSUE TITLE
possible memory leak in ad_http_get_content

### ISSUE THREAD

**Issue by levidurfee** [wolkykim/libasyncd#32]
I am occasionally getting extra characters when using `ad_http_get_content`.

`post = ad_http_get_content(conn, http->request.contentlength, 0);`

Below is a screenshot. Also, that is not a real API key.

![image](https://cloud.githubusercontent.com/assets/10798199/16571561/a6139dc0-422c-11e6-96ae-8db30687f4ca.png)

Most of the time it is just gibberish. I have seen the domain name appended to post. See screenshot below:

![image](https://cloud.githubusercontent.com/assets/10798199/16571578/e6715272-422c-11e6-9891-fb950f68c071.png)

I'm afraid there is a memory leak in my code or the `ad_http_get_content` function.

I am using SSL. If you need to see my code, it's currently in a private repo, but I can add you to it.

Thanks!

**Comment by wolkykim** [comment]
ad_http_get_content() does not terminate the return data. User is required to pass `storedsize` argument and check the actual data size.

> post = ad_http_get_content(conn, http->request.contentlength, 0);

So you can not assume the return is string and do printf("%s", post). It'll print some garbage data and possibly cause seg fault error.

Also note it's not guaranteed it returns all the content bytes as given `max` length. If there's lesser data in the buffer at the time of call, it'll just return the data it has. So you'll need to ensure this in your logic.... either in loop that issues another ad_http_get_content call for the remaining portion or check the in-buf size prior to call it.

**Comment by wolkykim** [comment]
I've updated the behavior of ad_http_get_content(). it will return null terminated data.
So if you update it with master and re-compile, it should work without an extra effort to convert the return data to string type and insert null terminator.

e6bcc19fa983fa61bef785913fabae00f778fff0

**Comment by levidurfee** [comment]
Thanks so much! Testing it now :)
